package ${daoPackage};

import ${entityFullName};
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

/**
 * Generated by Code-Generator.
 * Author: ProgrammerRabbit
 * http://github.com/ProgrammerRabbit
 */
public interface ${entityName}Dao {
    void insert(@Param("entity") ${entityName} entity);

    @Select("SELECT * FROM ${entityName} WHERE id = ${r'#{id}'}")
    ${entityName} getById(@Param("id") int id);

    @Select("SELECT * FROM ${entityName} WHERE ${r'${fieldName}'} = ${r'#{fieldValue}'}")
    List<${entityName}> getByField(@Param("fieldName") String filedName, @Param("fieldValue") Object fieldValue);

    void updateById(@Param("id") int id, @Param("entity") ${entityName} entity);

    @Delete("DELETE FROM ${entityName} WHERE id = ${r'#{id}'}")
    void deleteById(@Param("id") int id);
}