package com.github.programmerrabbit.dao;

import com.github.programmerrabbit.dao.entity.Request;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

/**
 * Generated by Code-Generator.
 * Author: ProgrammerRabbit
 * http://github.com/ProgrammerRabbit
 */
public interface RequestDao {
    void insert(@Param("entity") Request entity);

    @Select("SELECT * FROM Request WHERE id = #{id}")
    Request getById(@Param("id") int id);

    @Select("SELECT * FROM Request WHERE ${fieldName} = #{fieldValue}")
    List<Request> getByField(@Param("fieldName") String filedName, @Param("fieldValue") Object fieldValue);

    void updateById(@Param("id") int id, @Param("entity") Request entity);

    @Delete("DELETE FROM Request WHERE id = #{id}")
    void deleteById(@Param("id") int id);
}