package com.github.programmerrabbit.dao;

import com.github.programmerrabbit.dao.entity.Contact;
import org.junit.Test;

import javax.annotation.Resource;
import java.util.List;

/**
 * Generated by Code-Generator.
 * Author: ProgrammerRabbit
 * http://github.com/ProgrammerRabbit
 */
// TODO add spring4junit support
public class ContactDaoTest {
    @Resource
    private ContactDao dao;

    private final static int ID = 1; // TODO modify the value

    @Test
    public void insert() throws Exception {
        Contact entity = new Contact();
        // TODO fill entity
        dao.insert(entity);
    }

    @Test
    public void getById() throws Exception {
        Contact entity = dao.getById(ID);
        System.out.println(entity.toString());
    }

    @Test
    public void getByField() throws Exception {
        List<Contact> entityList = dao.getByField("", ""); // TODO fill fieldName and fieldValue
        for (Contact entity : entityList) {
            System.out.println(entity.toString());
        }
    }

    @Test
    public void updateById() throws Exception {
        Contact entity = new Contact();
        // TODO fill new entity
        dao.updateById(ID, entity);
    }

    @Test
    public void deleteById() throws Exception {
        dao.deleteById(ID);
    }

}